baseURL = 'https://lu-human.github.io/'
languageCode = 'en-us'
theme='charlolamode'


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 3

  [[menu.main]]
    identifier = "people"
    name = "People"
    url = "/people/"
    weight = 4

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 5

